import type { NFTProfile } from "./nft-types";

export const mockNFTProfiles: NFTProfile[] = [
  {
    tokenId: 1842,
    walletAddress: "0x1234...5678",
    userType: "creator",
    username: "TREXION VERIFIED",
    reputation: 92,
    mintedAt: "2025-01-15",
    isSoulbound: true,
    socialAccounts: [
      { platform: "Twitter", handle: "@trexion_gaming" },
      { platform: "YouTube", handle: "TREXION Gaming" },
    ],
    niche: "Gaming",
    audienceSize: 25000,
    engagement: 8.5,
  },
  {
    tokenId: 1001,
    walletAddress: "0xabcd...efgh",
    userType: "startup",
    username: "PixelForge Studios",
    reputation: 88,
    mintedAt: "2025-02-20",
    isSoulbound: true,
    industry: "Gaming",
    fundingStage: "Seed",
    communitySize: 12000,
    website: "https://pixelforge.example.com",
    objectives: ["Build AAA indie games", "Expand to mobile", "Community-driven development"],
  },
  {
    tokenId: 2045,
    walletAddress: "0x9876...5432",
    userType: "investor",
    username: "CryptoGamer",
    reputation: 95,
    mintedAt: "2025-03-10",
    isSoulbound: true,
    interests: ["Gaming", "Metaverse", "Web3"],
    ticketSize: { min: 5000, max: 100000 },
    sectorFocus: ["Gaming", "Entertainment", "Blockchain"],
  },
  {
    tokenId: 3002,
    walletAddress: "0x1111...2222",
    userType: "service_provider",
    username: "GameDev Pro",
    reputation: 90,
    mintedAt: "2025-01-28",
    isSoulbound: true,
    skills: ["Unity", "Unreal Engine", "Smart Contracts", "3D Modeling"],
    portfolio: [
      { title: "NFT Racing Game", url: "https://example.com/racing-game" },
      { title: "Metaverse Hub", url: "https://example.com/metaverse" },
    ],
    reviews: [
      { from: "PixelForge Studios", rating: 5, comment: "Excellent work!" },
      { from: "IndieDev DAO", rating: 4, comment: "Great delivery timeline." },
    ],
    verified: true,
  },
  {
    tokenId: 4120,
    walletAddress: "0x3333...4444",
    userType: "community",
    username: "Gaming DAO",
    reputation: 85,
    mintedAt: "2025-04-05",
    isSoulbound: true,
    members: 5000,
    topics: ["Gaming", "Web3", "Indie Dev"],
    region: "Global",
    activity: "high",
  },
];

export const currentUserProfile = mockNFTProfiles[0];
